### PR TITLE
Create React component

### PR DESCRIPTION
**Pull request by raksooo**
I've separated the parts that I believe is easy to reuse in the react component. I've used the example page to verify it's working so I've might have missed more advanced use cases. Is there anything I should test specifically?

### CODE REVIEW

**Comment by zachferland** [comment]
awesome, nice work @raksooo! at first glance and high level it makes sense to me, like how much was re useable in both and in the configs for the two builds. I'll review more in depth soon, hopefully tmrrw, or let me know when if still working on any parts. 

Was anything holding the react implementation back by trying to re use some much code in both? or anything that was really an anti pattern in react by doing it this way?

Not much for testing yet, baseline is basically the existing example for the current release, then seeing 1) if the react matches that visually and behavior wise 2) if the non react version still works the same as well

**Comment by raksooo** [comment]
Thanks! The react component isn't implemented yet so I'm still working on that one. I ran in to some issues with using the jsx both with react and jsx-render since both needs to have imports from their corresponding package. I think I've found a working solution now and will continue working on it tomorrow.

Current status is:
* The non-react widget works as before
* The react component fetches the profile data but does not render the html

I've got most parts of the react component working but didn't want to push until I had figured out how to do the react/jsx-render imports. I'll continue tomorrow!

**Comment by raksooo** [comment]
Current status:
* The react component renders the profile hover and it looks like the regular one (except for theme and html attrubutes)
* The copy button does not work

**Comment by raksooo** [comment]
Reusing the code has worked great so far. The only anti-pattern so far is in the copy button where in React it should be decided in render if an icon should be visible or not, whereas the current solution modifies the style property on the dom element directly.

**Comment by raksooo** [comment]
@zachferland I'm starting to feel pretty happy with the results. I think the react component matches both the js component and the specification in the issue description.

The JSX could probably need some refactoring though, to use more of the simplicity and strengths of JSX. The implementation is currently just a translation of the previous template strings, except for the onClick function in AddressBarTemplate.

To run it: ```npm run build:dist```, start the example server and visit the example page. The react components are displayed under the regular ones and should match them.

I've tested a production build in another component which works as expected, but I haven't tested the error handling.

Let me know what you think and if anything is missing, if you find something wierd or if I need to explain something.

**Comment by zachferland** [comment]
just a quick follow up to say I have been following commits, looked at it bit today, but nothing to add until I get some more time to got through it, I will soon, thanks for the comments, and the easy to follow commit messages!

**Comment by zachferland** [comment]
This looks good @raksooo !

Two minor regressions from original 
- the empty profile hover is different in react, visually includes extra wrapper and/or space above
- copy visual display/change doesn't work reliably, it think rerending and multiple calls of copy address or something is messing with timer. Like you mentioned probably something we want to treat separately in each implementation

For the build/example, could we have the example build in a separate webpack file and a separate npm script thats only run when the example is run. And then could we have the the react example in its own file(s), and served by the example server at `/react`

Again, great work, i think this basically covers all the already planned scope, and I am inclined to merge as soon as possible (once above followed up on), since huge step up for react apps. Any additional fixes/improvements can come in future PRs. 

Do you want to add the docs for the react component to README (they can go first)? Or I can add the docs when I do the release. 

Also our team will be working on some design/css improvement, maybe some additional components and/or options in the next week or two. We're excited to be able make the changes on top of this refactor

**Comment by raksooo** [comment]
@zachferland Good catch! I'll fix those issues in the coming days. I also thought about improving the error handling by wrapping formatProfileData in a try/catch.

Splitting the config sounds like a good idea!

Yeah sure, I'll update the README when I've fixed the remaining issues. Before releasing, "main" in package.json needs to updated to something that exports the react component. Main currently points to widget.js which does not export anything. Could we switch it to the react component or do we need to export widget.js? What do you think?

Looking forward to the design updates, and the profile card!

**Comment by zachferland** [comment]
Sounds good, oh yeah i was thinking about the export last time, probably will export react by default, the non react widget will most often just be used with script tag (and could have just have specific file path in readme for how to import non react widget if someone really wanted to)

Haven't thought about the error handling much, but yeah probably want to be able to catch any errors thrown anywhere in here.

**Comment by raksooo** [comment]
Sound good! I just noticed that I've already switched main to the react bundle.

**Comment by raksooo** [comment]
@zachferland All above issues are fixed now but I just realized the empty profile hover issue exists in the non-react version as well. It seems like getProfile doesn't throw an error anymore. I guess it is a result of https://github.com/3box/3box-js/issues/327.

I switched from the try/catch to checking if status is 'error'. I thought about leaving the try/catch just in case something happens but couldn't figure out why it should be needed. Do you think we should keep it?

Only the readme left. I'll get to that tomorrow!

**Comment by raksooo** [comment]
To make it possible to make a separate jsx-component and react-component, I made webpack use files ending in _react.jsx when building the react component. Such as CopyButton.jsx and CopyButton_react.jsx.

**Comment by raksooo** [comment]
@zachferland The readme is updated now as well as the issues mentioned above. Let me know if you find something more that is not working properly!

**Comment by zachferland** [comment]
ah yeah! i see what you are saying about the empty profile hover now, wasn't seeing in html component because of cache but see it now. Thanks for the cleanup up in the html component as well. hmm the empty profile is bit tricky, if profile has no elements shown in box, but technically has a profile, but think this is good for now, probably just create another template for that case in the future. 

Readme looks good!, along with build and example. Copy button makes sense to me. 

Anything you think left? would be glad to merge it any time now. Then plan a release sometime next week once we try it out a bit more, and if any more fixes, then can be done in new PRs building on this

**Comment by raksooo** [comment]
Yeah, the case with a profile without data should act like the empty one. It would probably be a quite easy fix. I might do a PR with that fix sometime.

Awesome! I can't come up with anything thats left except for some more testing. I'll also test it a bit more and let you know if I find anything.

**Comment by zachferland** [comment]
Alright great! I'm going to go ahead and merge it then, thanks @raksooo for all your work on this, good stuff, excited to get this out. I'll let you know next week when we are planning on releasing it, how testing/using it more goes, and if we also do any more work on it before the release.

@oznekenzo take a look here for how html/templating is organized now, and maybe we can try adding this react element already to our site next week  (cc @michaelsena )

**Comment by zachferland** [comment]
Merged 💯 👍 🎉

**Comment by raksooo** [comment]
Awesome! Glad I could help! I tested it some more in one of my projects where it first receives null as address and then it's updated with an address, and it worked as expected :+1:

**Pull request merged**
