### PR TITLE
Design V2 and new options 

### PR DESCRIPTION
**Pull request by zachferland**

### CODE REVIEW

**Review by zachferland — COMMENTED** [review]
Here is some notes so far: 

Need to sandbox errors, from bubbling up in the main app. Can't have hover crash devs app. Mainly try catch more things, unless error to signal incorrect use. One issue if it fails to fetch from API,  hover doesn't work, should still hover with some loading indicator. Is the loading state still in here? 

^ actually see now that looks like the loading state/transition is gone, seems like it would makes sense to have still, since loading not super fast and weird to not have any hover/feedback or copy address button until the api call completes. (related, also looks its waiting for all the calls on the page to complete? should inject data as each api call returns) 

with these changes, we basically don't have the non react element anymore, main thing here is the html.jsx file can't have anything react specific. The goal here was to have this file only have pure functions that return jsx template strings. At least doing that we won't break the non react component so much. Additional improvements to have them reach parity would be to pull some of the function that could be shared in ProfileHover.jsx like  checkWindowSize,  checkHasWeb3Mobile, etc into the utils so that can be shared between both react and non-react component. Basically the goal is to have as little code in the react component file as possible. 

Remove .DS_Store files

Otherwise react hover looks great. Awesome with cover image, even though a lot of img :) . Love the new footer.

**Comment by oznekenzo** [comment]
• I've now added more try catch statements. 
• I've kept all loading state/transitions? Is there a part of it you don't see?
• Which part is waiting for all calls to complete?  Are you referring to the line with `data.twitter || data.github || data.website)`, that will trigger when any one of those becomes available
• I can definitely move checkHasWeb3 mobile into utils.  I'm not quite sure how this is all converting to non-react, will the onMouseEnter function translate as well?  Then it seems the only issue with the html.jsx file is that it's using the `forwardRef` function, which is necessary for the ProfileHover.jsx file to pass down a ref that's being used to measure X & Y position and height/width of the hover element in the window

**Comment by zachferland** [comment]
``` 
I've now added more try catch statements.
```
great, still ok to throw error on invalid opts/inputs from dev, just not other failures 

``` 
I've kept all loading state/transitions? Is there a part of it you don't see?
```
never see the loading template hover, which said loading before (not sure if changed), basically i can't get any hover until the profile loads 

``` 
Which part is waiting for all calls to complete? Are you referring to the line with data.twitter || data.github || data.website), that will trigger when any one of those becomes available
```
nvm, nothing here, just looked this way before

```
 I can definitely move checkHasWeb3 mobile into utils. I'm not quite sure how this is all converting to non-react, will the onMouseEnter function translate as well? Then it seems the only issue with the html.jsx file is that it's using the forwardRef function, which is necessary for the ProfileHover.jsx file to pass down a ref that's being used to measure X & Y position and height/width of the hover element in the window
```
yeah forwardRef only necessary for this implementation exactly, but not too difficult (im pretty sure) to do without that, and pass ref to to the necessary dom node to use that same function. 

thanks for cleaning up props, almost did that in my PR too :) 

Added this PR  on top of this
https://github.com/3box/profile-hover/pull/32

This allows the non react component to still exist, just with out the mobile options and features. Basically it gets new templates/design, just not new functionality, mostly mobile stuff.

Also after looking in to it more, doing above, don't think its will be too hard to refactor copy state to work easily in each component, without too much additional code. 

But also think current state will be fine for release now

**Comment by oed** [comment]
Just pushed a commit to update my eth address :)

**Comment by zachferland** [comment]
@oznekenzo is this ready to merge?

**Comment by oznekenzo** [comment]
@zachferland you've tested the non-react component yeah?

**Comment by zachferland** [comment]
yup, and will also one last time on release branch after

**Pull request merged**
